version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mydb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      ConnectionStrings__DefaultConnection: "server=db;database=${MYSQL_DATABASE};user=${MYSQL_USER};password=${MYSQL_PASSWORD};"
      ASPNETCORE_URLS: "http://0.0.0.0:5035"
    ports:
      - "5035:8080"
    depends_on:
      - db

volumes:
  db_data:
