name: Build and Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check (SCA)
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Skylance Backend"
          path: "."
          format: "ALL"
          out: "dependency-check-report"
        continue-on-error: true  # Don't fail the build

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report

      - name: Set up Docker Buildx (for cross-platform builds)
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 -t tallmelon/skylance-backend-final:latest --push .

      - name: Deploy to DigitalOcean via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /root
            docker pull tallmelon/skylance-backend-final:latest
            docker-compose down
            docker-compose up -d

      - name: Run OWASP ZAP Baseline Scan
        run: |
          mkdir -p zap-temp
          docker run -i \
            -v ${{ github.workspace }}/zap-temp:/zap/wrk/:rw \
            --user root \
            zaproxy/zap-stable zap-baseline.py \
            -t "http://${{ secrets.DROPLET_IP }}" \
            -r /zap/wrk/zap_baseline_report.html \
            -J /zap/wrk/zap_baseline_report.json \
            -T 10
        continue-on-error: true

      - name: Upload ZAP Reports
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-html
          path: zap-temp/zap_baseline_report.html

      - name: Upload ZAP JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-json
          path: zap-temp/zap_baseline_report.json